-- database.sql - HR365 schema inicial
CREATE DATABASE IF NOT EXISTS hr365_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hr365_db;

CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  role VARCHAR(32) NULL,
  status VARCHAR(16) NULL DEFAULT 'ACTIVO',
  code VARCHAR(32) NULL,
  avatar VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

